### PR TITLE
Adds text wrapping option to barplot, heatplot, dotplot, & ridgeplot

### PR DESCRIPTION
**Pull request by RichardJActon**
Adds the option `label_wrap_width` which defaults to 30 at the moment
This addresses the issue arrising from long terms for gene sets causing your graphs to be too small or sometimes even competely hidden as a result of very long names.

`enrichplot:::barplot.enrichResult(ex, label_wrap_width = 100)`

image

`enrichplot:::barplot.enrichResult(ex, label_wrap_width = 20)`

image

*NB Underscores are removed from names to allow wrapping*

### CODE REVIEW

**Comment by GuangchuangYu** [comment]
It is a neat idea to have this feature. 

However, there are two concerns:

1. stringr is a huge dependency and I personally would not like to import this pkg.
2. I believe a labeller parameter that accept a user defined function would be a better solution, (e.g. image_fun example provided in <http://yulab-smu.top/treedata-book/ggimage-tips.html>). In this way, not only `str_wrap` but also other effects on the axis label can be applied.

**Comment by GuangchuangYu** [comment]
hadley also trying to create a replacement for stringr, see <https://github.com/hadley/stringb>.

After re-thinkg this problem, I think maybe your approach for introducing a new parameter is more user friendly, especially for newbie. 

But I really don't want to import stringr.

So I write a `my_str_wrap` function for you, maybe you can incorporate it and update the code accordingly.

```r
my_str_wrap <- function(string, width) {
    x <- gregexpr(' ', string)
    vapply(seq_along(x), 
        FUN = function(i) {
            y <- x[[i]]
            idx <- (y - c(0, y[-length(y)])) > width
            idx <- which(idx)
            start <- c(0, y[idx] + 1)
            end <- c(y[idx] - 1, nchar(string[i]))
            words <- substring(string[i], start, end)
            paste0(words, collapse="\n")
            },
        FUN.VALUE = character(1)
    )
}
```

example:

```r
> x
[1] "abc def xxxxx"
> my_str_wrap(x, 3)
[1] "abc\ndef\nxxxxx"
> my_str_wrap(c(x,x), 3)
[1] "abc\ndef\nxxxxx" "abc\ndef\nxxxxx"
```

**Comment by RichardJActon** [comment]
Thank you for looking over my PR.
I understand the concern about a large dependency like `stringr` I will adjust my fork to use the the wrap function you provided.
I have a couple of questions.

- Would the `utilities.R ` file be your prefered location for the `my_str_wrap` function?
- What do you think of my choice of a default wrap length of 30 characters? I was a little uncertain about this as it is probably a nice default going forward but previous users may have optimised outputs around the existing behaviour which could be mostly maintained simply by setting a higher default e.g. 100 characters.

I also see your point about greater flexibility from providing a user specifiable labeller function. Perhaps we could have the best of both worlds by replacing my `label_wrap_width` argument with `label_format` which if provided with a numeric value will simply string wrap by default and if provided with a function will instead set `labels = user_defined_function()` within the scale function?

**Comment by GuangchuangYu** [comment]
1.  Yes.
2. I think 30 is OK.

3. `label_format` that supports both string width and user defined function is a neat idea and I would prefer this solution.

**Comment by GuangchuangYu** [comment]
thanks.

**Pull request merged**
