### PR TITLE
Fix bugs when enrich result only has one line

### PR DESCRIPTION
**Pull request by crotoc**
emapplot stops and throws an error when there is only one line in enrichment result.
emapplot_cluster stops and throws an error saying the graph is undirected when there is only one line in enrichment results.

### CODE REVIEW

**Comment by huerqiang** [comment]
Please provide data and code to reflect this bug, thanks.

**Comment by GuangchuangYu** [comment]
>emapplot stops and throws an error when there is only one line in enrichment result.

It is easy to test whether this bug is exists, and you should definitely do that. @huerqiang

**Comment by GuangchuangYu** [comment]
fixed by <https://github.com/YuLab-SMU/enrichplot/pull/95>.

**Comment by crotoc** [comment]
Thanks very much!

**Pull request closed without merging**
